---
- name: Parsear el CSV para extraer los datos de los usuarios
  community.general.read_csv:
    path: usuarios.csv
  register: datos_usuarios
  
- name: Parsear el CSV para extraer los datos de los grupos
  community.general.read_csv:
    path: grupos.csv
  register: datos_grupos

- name: Crear los grupos
  ansible.builtin.group:
    name: "{{ item.nombre }}"
    state: present
  loop: "{{ datos_grupos.list }}"

- name: Crear los usuarios
  ansible.builtin.user:
    name: "{{ item.nombre }}"
    create_home: false
    password: "{{ item.password | password_hash('sha512') }}"
    shell: "/bin/false"
    groups: "{{ item.grupo }}"
    update_password: on_create
  loop: "{{ datos_usuarios.list }}"
  
- name: Crear los usuarios para samba
  shell: "(echo {{ item.smb_password }}; echo {{ item.smb_password }}) | smbpasswd -s -a {{ item.nombre }}"
  loop: "{{ datos_usuarios.list }}"
  
  # ansible-galaxy collection install community.general
  # funciona solo en localhost